/**
 * AUTO-GENERATED — do not edit by hand.
 * Generated by `pnpm --filter @horus/db gen:migrations` from packages/db/drizzle/*.sql.
 *
 * The published CLI bundle (apps/horus/dist/index.cjs) ships as a single file with
 * NO node_modules and NO drizzle/ folder, so the embedded-pglite local database
 * cannot read migrations from disk. Instead the migration SQL is inlined here and
 * applied idempotently by createLocalDb() (see client.ts).
 */

export interface EmbeddedMigration {
  /** Drizzle migration tag, e.g. "0000_redundant_kabuki". */
  readonly tag: string;
  /** Individual SQL statements (drizzle statement-breakpoints already split out). */
  readonly statements: readonly string[];
}

export const EMBEDDED_MIGRATIONS: readonly EmbeddedMigration[] = [
  {
    "tag": "0000_redundant_kabuki",
    "statements": [
      "CREATE TABLE \"evidence\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"investigation_id\" uuid NOT NULL,\n\t\"source\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"timestamp\" timestamp with time zone,\n\t\"relevance\" real DEFAULT 0 NOT NULL,\n\t\"payload\" jsonb,\n\t\"links\" jsonb,\n\t\"provenance\" jsonb,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"hypotheses\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"investigation_id\" uuid NOT NULL,\n\t\"rank\" integer NOT NULL,\n\t\"statement\" text NOT NULL,\n\t\"score\" real DEFAULT 0 NOT NULL,\n\t\"supporting_evidence\" uuid[],\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"investigations\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"incident_input\" jsonb NOT NULL,\n\t\"status\" text DEFAULT 'open' NOT NULL,\n\t\"summary\" text,\n\t\"narrative\" jsonb,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"provider_cache\" (\n\t\"provider\" text NOT NULL,\n\t\"cache_key\" text NOT NULL,\n\t\"payload\" jsonb,\n\t\"expires_at\" timestamp with time zone,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"provider_cache_provider_cache_key_pk\" PRIMARY KEY(\"provider\",\"cache_key\")\n);",
      "CREATE TABLE \"queue_edges\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"queue_name\" text NOT NULL,\n\t\"producer_symbol\" text,\n\t\"producer_file\" text,\n\t\"worker_symbol\" text,\n\t\"worker_file\" text,\n\t\"source\" text DEFAULT 'stitcher' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"repositories\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"path\" text NOT NULL,\n\t\"last_indexed_at\" timestamp with time zone,\n\t\"source_status\" jsonb,\n\t\"stale\" boolean DEFAULT true NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"repositories_name_unique\" UNIQUE(\"name\")\n);",
      "ALTER TABLE \"evidence\" ADD CONSTRAINT \"evidence_investigation_id_investigations_id_fk\" FOREIGN KEY (\"investigation_id\") REFERENCES \"public\".\"investigations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"hypotheses\" ADD CONSTRAINT \"hypotheses_investigation_id_investigations_id_fk\" FOREIGN KEY (\"investigation_id\") REFERENCES \"public\".\"investigations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"evidence_investigation_idx\" ON \"evidence\" USING btree (\"investigation_id\");",
      "CREATE INDEX \"hypotheses_investigation_idx\" ON \"hypotheses\" USING btree (\"investigation_id\");",
      "CREATE INDEX \"queue_edges_queue_name_idx\" ON \"queue_edges\" USING btree (\"queue_name\");"
    ]
  },
  {
    "tag": "0001_flaky_lester",
    "statements": [
      "CREATE TABLE \"findings\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"investigation_id\" uuid NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"detail\" text,\n\t\"confidence\" real DEFAULT 0 NOT NULL,\n\t\"evidence_ids\" uuid[],\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"incident_memory\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"investigation_id\" uuid,\n\t\"title\" text NOT NULL,\n\t\"summary\" text,\n\t\"signature\" text,\n\t\"tags\" text[],\n\t\"payload\" jsonb,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"projects\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"projects_name_unique\" UNIQUE(\"name\")\n);",
      "ALTER TABLE \"repositories\" ADD COLUMN \"project_id\" uuid;",
      "ALTER TABLE \"findings\" ADD CONSTRAINT \"findings_investigation_id_investigations_id_fk\" FOREIGN KEY (\"investigation_id\") REFERENCES \"public\".\"investigations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"incident_memory\" ADD CONSTRAINT \"incident_memory_investigation_id_investigations_id_fk\" FOREIGN KEY (\"investigation_id\") REFERENCES \"public\".\"investigations\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "CREATE INDEX \"findings_investigation_idx\" ON \"findings\" USING btree (\"investigation_id\");",
      "CREATE INDEX \"incident_memory_signature_idx\" ON \"incident_memory\" USING btree (\"signature\");",
      "ALTER TABLE \"repositories\" ADD CONSTRAINT \"repositories_project_id_projects_id_fk\" FOREIGN KEY (\"project_id\") REFERENCES \"public\".\"projects\"(\"id\") ON DELETE set null ON UPDATE no action;"
    ]
  },
  {
    "tag": "0002_reflective_the_enforcers",
    "statements": [
      "ALTER TABLE \"hypotheses\" ADD COLUMN \"verdict\" text;"
    ]
  },
  {
    "tag": "0003_past_chat",
    "statements": [
      "ALTER TABLE \"investigations\" ADD COLUMN \"report\" jsonb;"
    ]
  },
  {
    "tag": "0004_queue_edges_project",
    "statements": [
      "ALTER TABLE \"queue_edges\" ADD COLUMN \"project\" text;",
      "CREATE INDEX \"queue_edges_source_project_idx\" ON \"queue_edges\" (\"source\",\"project\");"
    ]
  },
  {
    "tag": "0005_incident_memory_project",
    "statements": [
      "ALTER TABLE \"incident_memory\" ADD COLUMN \"project\" text;",
      "UPDATE \"incident_memory\" im\nSET \"project\" = (\n  SELECT i.incident_input->>'repo'\n  FROM \"investigations\" i\n  WHERE i.id = im.investigation_id\n    AND i.incident_input->>'repo' IS NOT NULL\n)\nWHERE im.investigation_id IS NOT NULL AND im.project IS NULL;",
      "CREATE INDEX \"incident_memory_project_idx\" ON \"incident_memory\" (\"project\");"
    ]
  },
  {
    "tag": "0006_source_intelligence_metadata",
    "statements": []
  },
  {
    "tag": "0007_memory_item",
    "statements": [
      "CREATE TABLE \"memory_item\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"claim\" text NOT NULL,\n\t\"scope\" text NOT NULL,\n\t\"source\" text NOT NULL,\n\t\"evidence\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"confidence\" real NOT NULL,\n\t\"status\" text DEFAULT 'fresh' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"last_verified_at\" timestamp with time zone,\n\t\"last_verified_hash\" text,\n\t\"org_id\" text,\n\t\"workspace_id\" text,\n\t\"repo\" text NOT NULL,\n\t\"user_id\" text,\n\t\"visibility\" text DEFAULT 'private' NOT NULL,\n\t\"payload\" jsonb\n);",
      "CREATE TABLE \"memory_link\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"from_memory_id\" text NOT NULL,\n\t\"rel\" text NOT NULL,\n\t\"to_kind\" text NOT NULL,\n\t\"to_ref\" text NOT NULL,\n\t\"to_file_path\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"memory_audit\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"memory_id\" text NOT NULL,\n\t\"action\" text NOT NULL,\n\t\"actor\" jsonb NOT NULL,\n\t\"from_status\" text,\n\t\"to_status\" text,\n\t\"note\" text,\n\t\"at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"memory_link\" ADD CONSTRAINT \"memory_link_from_memory_id_memory_item_id_fk\" FOREIGN KEY (\"from_memory_id\") REFERENCES \"public\".\"memory_item\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"memory_audit\" ADD CONSTRAINT \"memory_audit_memory_id_memory_item_id_fk\" FOREIGN KEY (\"memory_id\") REFERENCES \"public\".\"memory_item\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"memory_item_repo_idx\" ON \"memory_item\" USING btree (\"repo\");",
      "CREATE INDEX \"memory_item_scope_idx\" ON \"memory_item\" USING btree (\"scope\");",
      "CREATE INDEX \"memory_item_status_idx\" ON \"memory_item\" USING btree (\"status\");",
      "CREATE INDEX \"memory_item_tenancy_idx\" ON \"memory_item\" USING btree (\"org_id\",\"workspace_id\",\"repo\",\"user_id\");",
      "CREATE INDEX \"memory_link_from_idx\" ON \"memory_link\" USING btree (\"from_memory_id\");",
      "CREATE INDEX \"memory_link_to_idx\" ON \"memory_link\" USING btree (\"to_kind\",\"to_ref\");",
      "CREATE INDEX \"memory_audit_memory_idx\" ON \"memory_audit\" USING btree (\"memory_id\");"
    ]
  }
];
