/**
 * HOR-26 — Unit tests for generatePostmortem (vitest, PURE).
 * No I/O, no DB, no external deps. All assertions guard indexed access.
 */

import { describe, it, expect } from 'vitest';
import { generatePostmortem, validatePostmortemGrounding } from './postmortem.js';
import type { InvestigationReport } from './types.js';
import type { Evidence } from '@horus/core';
import type { ValidatedHypothesis } from './validate.js';
import type { CauseCandidate } from './types.js';

// ---------------------------------------------------------------------------
// Synthetic fixtures
// ---------------------------------------------------------------------------

const syntheticEvidence: Evidence = {
  id: 'ev-abcdef1234567890',
  source: 'history',
  kind: 'commit',
  title: 'fix: reduce connection pool timeout',
  relevance: 0.8,
  payload: {},
  links: {},
  provenance: { query: 'git log --since=7.days', collectedAt: '2026-06-14T10:00:00Z' },
};

const syntheticHypothesis: ValidatedHypothesis = {
  id: 'hyp-001',
  category: 'Deployment regression',
  statement: 'A recent commit reduced the connection pool timeout, causing downstream timeouts.',
  confidence: 0.75,
  priorConfidence: 0.6,
  verdict: 'supported',
  supportingPresent: 1,
  contradictingPresent: 0,
  rationale: '1 supporting / 0 contradicting evidence present.',
  supportingEvidenceIds: ['ev-abcdef1234567890'],
  contradictingEvidenceIds: [],
  missingEvidence: ['runtime metrics'],
};

const syntheticSuspectedCause: CauseCandidate = {
  id: 'cause:infrastructure',
  title: 'Connection pool exhaustion under peak load.',
  category: 'infrastructure',
  sourceEvidenceIds: ['ev-abcdef1234567890'],
  affectedNodeIds: [],
  baseScore: 0.65,
  finalScore: 0.72,
  confidence: 0.72,
  band: 'likely',
  explanations: [],
};

const syntheticReport: InvestigationReport = {
  id: 'inv-test-001',
  input: {
    hint: 'OrderService latency spike',
    service: 'order-service',
    since: 'HEAD~10',
  },
  summary: 'A latency spike in OrderService was detected after a recent deployment.',
  seeds: [],
  evidence: [syntheticEvidence],
  timeline: {
    events: [
      {
        order: 1,
        at: '2026-06-14T09:00:00Z',
        kind: 'commit',
        title: 'Deployment of v2.3.1 to production',
        evidenceIds: ['ev-abcdef1234567890'],
        boundaryCrossing: false,
      },
    ],
    boundaryCrossings: [],
  },
  correlation: {
    chains: [],
    groups: [],
    missing: [],
  },
  findings: [],
  suspectedCauses: [syntheticSuspectedCause],
  hypotheses: [syntheticHypothesis],
  similarIncidents: [],
  gapAnalysis: {
    gaps: [
      {
        dimension: 'metrics',
        why: 'No metrics — cannot see latency/error-rate trends.',
        nextSource: 'Prometheus provider (HOR-11)',
        confidenceImpact: 0.1,
      },
    ],
    blindSpots: ['Cannot validate latency-based hypotheses.'],
    confidenceCeiling: 0.9,
  },
  graph: { nodes: [], edges: [] },
  confidence: 0.65,
  nextActions: [
    'Verify connection pool settings against load test results',
    'Add alerting for pool saturation',
  ],
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('generatePostmortem', () => {
  it('produces a non-empty string', () => {
    const out = generatePostmortem(syntheticReport);
    expect(typeof out).toBe('string');
    expect(out.length).toBeGreaterThan(0);
  });

  it('contains the DRAFT banner', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain(
      '_Draft generated by Horus — deterministic, no AI. Edit freely; Horus drafts, it does not dictate._',
    );
  });

  it('contains all required section headers', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain('## Summary');
    expect(out).toContain('## Impact');
    expect(out).toContain('## Timeline');
    expect(out).toContain('## Contributing factors');
    expect(out).toContain('## Root cause');
    expect(out).toContain('## Evidence');
    expect(out).toContain('## Lessons learned');
    expect(out).toContain('## Follow-up actions');
  });

  it('lists the supported hypothesis under Contributing factors', () => {
    const out = generatePostmortem(syntheticReport);
    const hypothesis = syntheticReport.hypotheses[0];
    // Guard indexed access — hypothesis must exist
    expect(hypothesis).toBeDefined();
    if (hypothesis) {
      expect(out).toContain(hypothesis.statement);
    }
  });

  it('has at least one checkbox item in Follow-up actions', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain('- [ ]');
  });

  it('mentions the nextActions in follow-up actions', () => {
    const out = generatePostmortem(syntheticReport);
    const firstAction = syntheticReport.nextActions[0];
    expect(firstAction).toBeDefined();
    if (firstAction) {
      expect(out).toContain(firstAction);
    }
  });

  it('wires the gap nextSource into follow-up actions', () => {
    const out = generatePostmortem(syntheticReport);
    const gap = syntheticReport.gapAnalysis.gaps[0];
    expect(gap).toBeDefined();
    if (gap) {
      expect(out).toContain(gap.nextSource);
    }
  });

  it('includes the summary text', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain(syntheticReport.summary);
  });

  it('includes the timeline event title', () => {
    const out = generatePostmortem(syntheticReport);
    const event = syntheticReport.timeline.events[0];
    expect(event).toBeDefined();
    if (event) {
      expect(out).toContain(event.title);
    }
  });

  it('includes the evidence short id and title', () => {
    const out = generatePostmortem(syntheticReport);
    // First 8 chars of the evidence id
    expect(out).toContain('ev-abcde');
    expect(out).toContain(syntheticEvidence.title);
  });

  it('includes a lessons-learned entry for each gap', () => {
    const out = generatePostmortem(syntheticReport);
    const gap = syntheticReport.gapAnalysis.gaps[0];
    expect(gap).toBeDefined();
    if (gap) {
      // The lesson should mention the dimension
      expect(out).toContain(gap.dimension);
    }
  });

  it('marks the root cause as a CANDIDATE not a certainty', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain('**CANDIDATE**');
    // Should never assert certainty — check that "confirmed" is qualified
    // The word "confirmed" only appears in the uncertainty caveat context
    expect(out).not.toContain('This is the confirmed root cause');
  });
});

// ---------------------------------------------------------------------------
// HOR-112 — Evidence grounding validation
// ---------------------------------------------------------------------------

describe('validatePostmortemGrounding', () => {
  it('passes for a report with evidence (all cited IDs are known)', () => {
    const out = generatePostmortem(syntheticReport);
    const result = validatePostmortemGrounding(syntheticReport, out);
    expect(result.valid).toBe(true);
    expect(result.unknownIds).toHaveLength(0);
  });

  it('passes for a report with no evidence (nothing is cited)', () => {
    const emptyReport: InvestigationReport = {
      ...syntheticReport,
      evidence: [],
      hypotheses: [],
      suspectedCauses: [],
      timeline: { events: [], boundaryCrossings: [] },
    };
    const out = generatePostmortem(emptyReport);
    const result = validatePostmortemGrounding(emptyReport, out);
    expect(result.valid).toBe(true);
    expect(result.unknownIds).toHaveLength(0);
  });

  it('passes for multiple evidence items (all IDs mapped)', () => {
    const secondEvidence: typeof syntheticEvidence = {
      ...syntheticEvidence,
      id: 'ev-zzzzzzzz99999999',
      title: 'Second piece of evidence',
      kind: 'impact',
    };
    const richReport: InvestigationReport = {
      ...syntheticReport,
      evidence: [syntheticEvidence, secondEvidence],
    };
    const out = generatePostmortem(richReport);
    const result = validatePostmortemGrounding(richReport, out);
    expect(result.valid).toBe(true);
    expect(result.unknownIds).toHaveLength(0);
  });

  it('fails when the postmortem text contains a phantom (unknown) evidence ID', () => {
    const out = generatePostmortem(syntheticReport);
    // Inject a fake 8-char citation that does not exist in the report
    const tampered = out + '\n- `phantom0` [fake/kind] injected reference\n';
    const result = validatePostmortemGrounding(syntheticReport, tampered);
    expect(result.valid).toBe(false);
    expect(result.unknownIds).toContain('phantom0');
  });

  it('returns all unknown IDs when multiple phantoms are present', () => {
    const out = generatePostmortem(syntheticReport);
    const tampered =
      out +
      '\n- `phantom0` [fake/kind] first\n' +
      '- `ghost123` [fake/kind] second\n';
    const result = validatePostmortemGrounding(syntheticReport, tampered);
    expect(result.valid).toBe(false);
    expect(result.unknownIds).toContain('phantom0');
    expect(result.unknownIds).toContain('ghost123');
  });

  it('ignores genuine 8-char content that matches the known ID (no false positive)', () => {
    // The real ID prefix ev-abcde appears in backtick form; confirm it is NOT flagged
    const out = generatePostmortem(syntheticReport);
    const result = validatePostmortemGrounding(syntheticReport, out);
    expect(result.unknownIds).not.toContain('ev-abcde');
  });
});

// ---------------------------------------------------------------------------
// HOR-112 — Missing evidence: honest "no data" wording
// ---------------------------------------------------------------------------

describe('generatePostmortem — missing evidence wording', () => {
  const noEvidenceReport: InvestigationReport = {
    ...syntheticReport,
    evidence: [],
    hypotheses: [],
    suspectedCauses: [],
    timeline: { events: [], boundaryCrossings: [] },
    gapAnalysis: { gaps: [], blindSpots: [], confidenceCeiling: 1 },
    nextActions: [],
  };

  it('says "No evidence was collected" in the Evidence section', () => {
    const out = generatePostmortem(noEvidenceReport);
    expect(out).toContain('_No evidence was collected._');
  });

  it('says no impact evidence was captured', () => {
    const out = generatePostmortem(noEvidenceReport);
    expect(out).toContain('_No impact evidence was captured during this investigation._');
  });

  it('says no confirmed contributing factors when evidence is empty', () => {
    const out = generatePostmortem(noEvidenceReport);
    expect(out).toContain('_No confirmed contributing factors were identified.');
  });

  it('says no candidate root cause when both hypotheses and causes are empty', () => {
    const out = generatePostmortem(noEvidenceReport);
    expect(out).toContain('_No candidate root cause could be determined');
  });

  it('still produces all required section headers even with no evidence', () => {
    const out = generatePostmortem(noEvidenceReport);
    expect(out).toContain('## Evidence');
    expect(out).toContain('## Summary');
    expect(out).toContain('## Contributing factors');
    expect(out).toContain('## Root cause');
  });

  it('follow-up actions defaults to the review checkbox when no next actions', () => {
    const out = generatePostmortem(noEvidenceReport);
    expect(out).toContain('- [ ] Review this postmortem with the team');
  });
});

// ---------------------------------------------------------------------------
// HOR-112 — Weak evidence: unconfirmed / qualified language
// ---------------------------------------------------------------------------

describe('generatePostmortem — weak evidence / unconfirmed wording', () => {
  const weakReport: InvestigationReport = {
    ...syntheticReport,
    // No supported hypotheses — only suspected causes
    hypotheses: [
      {
        ...syntheticReport.hypotheses[0]!,
        verdict: 'weakened',
      },
    ],
  };

  it('labels the root cause candidate as unconfirmed when no hypothesis is supported', () => {
    const out = generatePostmortem(weakReport);
    expect(out).toContain('unconfirmed');
  });

  it('still emits CANDIDATE heading when only a suspected cause exists', () => {
    const out = generatePostmortem(weakReport);
    expect(out).toContain('**CANDIDATE**');
  });

  it('mentions evidence gaps in the root-cause caveat', () => {
    const out = generatePostmortem(weakReport);
    expect(out).toContain('evidence gaps remain');
  });

  it('does not claim certainty (no "confirmed root cause" text)', () => {
    const out = generatePostmortem(weakReport);
    expect(out).not.toContain('confirmed root cause');
  });
});
