/**
 * HOR-26 — Unit tests for generatePostmortem (vitest, PURE).
 * No I/O, no DB, no external deps. All assertions guard indexed access.
 */

import { describe, it, expect } from 'vitest';
import { generatePostmortem } from './postmortem.js';
import type { InvestigationReport } from './types.js';
import type { Evidence } from '@horus/core';
import type { ValidatedHypothesis } from './validate.js';
import type { CauseCandidate } from './types.js';

// ---------------------------------------------------------------------------
// Synthetic fixtures
// ---------------------------------------------------------------------------

const syntheticEvidence: Evidence = {
  id: 'ev-abcdef1234567890',
  source: 'history',
  kind: 'commit',
  title: 'fix: reduce connection pool timeout',
  relevance: 0.8,
  payload: {},
  links: {},
  provenance: { query: 'git log --since=7.days', collectedAt: '2026-06-14T10:00:00Z' },
};

const syntheticHypothesis: ValidatedHypothesis = {
  id: 'hyp-001',
  category: 'Deployment regression',
  statement: 'A recent commit reduced the connection pool timeout, causing downstream timeouts.',
  confidence: 0.75,
  priorConfidence: 0.6,
  verdict: 'supported',
  supportingPresent: 1,
  contradictingPresent: 0,
  rationale: '1 supporting / 0 contradicting evidence present.',
  supportingEvidenceIds: ['ev-abcdef1234567890'],
  contradictingEvidenceIds: [],
  missingEvidence: ['runtime metrics'],
};

const syntheticSuspectedCause: CauseCandidate = {
  id: 'cause:infrastructure',
  title: 'Connection pool exhaustion under peak load.',
  category: 'infrastructure',
  sourceEvidenceIds: ['ev-abcdef1234567890'],
  affectedNodeIds: [],
  baseScore: 0.65,
  finalScore: 0.72,
  confidence: 0.72,
  band: 'likely',
  explanations: [],
};

const syntheticReport: InvestigationReport = {
  id: 'inv-test-001',
  input: {
    hint: 'OrderService latency spike',
    service: 'order-service',
    since: 'HEAD~10',
  },
  summary: 'A latency spike in OrderService was detected after a recent deployment.',
  seeds: [],
  evidence: [syntheticEvidence],
  timeline: {
    events: [
      {
        order: 1,
        at: '2026-06-14T09:00:00Z',
        kind: 'commit',
        title: 'Deployment of v2.3.1 to production',
        evidenceIds: ['ev-abcdef1234567890'],
        boundaryCrossing: false,
      },
    ],
    boundaryCrossings: [],
  },
  correlation: {
    chains: [],
    groups: [],
    missing: [],
  },
  findings: [],
  suspectedCauses: [syntheticSuspectedCause],
  hypotheses: [syntheticHypothesis],
  similarIncidents: [],
  gapAnalysis: {
    gaps: [
      {
        dimension: 'metrics',
        why: 'No metrics — cannot see latency/error-rate trends.',
        nextSource: 'Prometheus provider (HOR-11)',
        confidenceImpact: 0.1,
      },
    ],
    blindSpots: ['Cannot validate latency-based hypotheses.'],
    confidenceCeiling: 0.9,
  },
  graph: { nodes: [], edges: [] },
  confidence: 0.65,
  nextActions: [
    'Verify connection pool settings against load test results',
    'Add alerting for pool saturation',
  ],
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('generatePostmortem', () => {
  it('produces a non-empty string', () => {
    const out = generatePostmortem(syntheticReport);
    expect(typeof out).toBe('string');
    expect(out.length).toBeGreaterThan(0);
  });

  it('contains the DRAFT banner', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain(
      '_Draft generated by Horus — deterministic, no AI. Edit freely; Horus drafts, it does not dictate._',
    );
  });

  it('contains all required section headers', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain('## Summary');
    expect(out).toContain('## Impact');
    expect(out).toContain('## Timeline');
    expect(out).toContain('## Contributing factors');
    expect(out).toContain('## Root cause');
    expect(out).toContain('## Evidence');
    expect(out).toContain('## Lessons learned');
    expect(out).toContain('## Follow-up actions');
  });

  it('lists the supported hypothesis under Contributing factors', () => {
    const out = generatePostmortem(syntheticReport);
    const hypothesis = syntheticReport.hypotheses[0];
    // Guard indexed access — hypothesis must exist
    expect(hypothesis).toBeDefined();
    if (hypothesis) {
      expect(out).toContain(hypothesis.statement);
    }
  });

  it('has at least one checkbox item in Follow-up actions', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain('- [ ]');
  });

  it('mentions the nextActions in follow-up actions', () => {
    const out = generatePostmortem(syntheticReport);
    const firstAction = syntheticReport.nextActions[0];
    expect(firstAction).toBeDefined();
    if (firstAction) {
      expect(out).toContain(firstAction);
    }
  });

  it('wires the gap nextSource into follow-up actions', () => {
    const out = generatePostmortem(syntheticReport);
    const gap = syntheticReport.gapAnalysis.gaps[0];
    expect(gap).toBeDefined();
    if (gap) {
      expect(out).toContain(gap.nextSource);
    }
  });

  it('includes the summary text', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain(syntheticReport.summary);
  });

  it('includes the timeline event title', () => {
    const out = generatePostmortem(syntheticReport);
    const event = syntheticReport.timeline.events[0];
    expect(event).toBeDefined();
    if (event) {
      expect(out).toContain(event.title);
    }
  });

  it('includes the evidence short id and title', () => {
    const out = generatePostmortem(syntheticReport);
    // First 8 chars of the evidence id
    expect(out).toContain('ev-abcde');
    expect(out).toContain(syntheticEvidence.title);
  });

  it('includes a lessons-learned entry for each gap', () => {
    const out = generatePostmortem(syntheticReport);
    const gap = syntheticReport.gapAnalysis.gaps[0];
    expect(gap).toBeDefined();
    if (gap) {
      // The lesson should mention the dimension
      expect(out).toContain(gap.dimension);
    }
  });

  it('marks the root cause as a CANDIDATE not a certainty', () => {
    const out = generatePostmortem(syntheticReport);
    expect(out).toContain('**CANDIDATE**');
    // Should never assert certainty — check that "confirmed" is qualified
    // The word "confirmed" only appears in the uncertainty caveat context
    expect(out).not.toContain('This is the confirmed root cause');
  });
});
