/**
 * HOR-26 — Deterministic incident postmortem generator.
 *
 * Turns a completed (persisted) InvestigationReport into a high-quality DRAFT
 * postmortem document. Pure Markdown, no AI, no I/O. Humans edit the draft;
 * Horus drafts, it does not dictate.
 */

import type { InvestigationReport } from './types.js';

/** Short, citable evidence id (first 8 chars). */
function shortId(id: string): string {
  return id.slice(0, 8);
}

/**
 * Verify that every evidence short-ID cited in a generated postmortem text
 * maps back to an evidence item in the source report.
 *
 * The check is structural: `generatePostmortem` cites IDs only from the
 * report's evidence array, so any unknown ID signals tampering or a bug.
 * Returns `valid: true` when all cited IDs are known; otherwise lists the
 * unknown ones.
 */
export function validatePostmortemGrounding(
  r: InvestigationReport,
  postmortemText: string,
): { valid: boolean; unknownIds: string[] } {
  const knownShortIds = new Set(r.evidence.map((e) => e.id.slice(0, 8)));

  const cited = new Set<string>();

  // Pattern 1: backtick-wrapped 8-char IDs — `ev-abcde` (impact + contributing factors sections)
  const backtickRe = /`([a-zA-Z0-9_-]{8})`/g;
  let m: RegExpExecArray | null;
  while ((m = backtickRe.exec(postmortemText)) !== null) {
    cited.add(m[1]!);
  }

  // Pattern 2: evidence section list items — "- ev-abcde [source/kind]"
  const listRe = /^- ([a-zA-Z0-9_-]{8}) \[/gm;
  while ((m = listRe.exec(postmortemText)) !== null) {
    cited.add(m[1]!);
  }

  const unknownIds = [...cited].filter((id) => !knownShortIds.has(id));
  return { valid: unknownIds.length === 0, unknownIds };
}

/**
 * Generate a deterministic DRAFT postmortem Markdown document from a completed
 * investigation report. All sections are derived mechanically from `r`; no
 * randomness, no AI inference.
 */
export function generatePostmortem(r: InvestigationReport): string {
  const lines: string[] = [];

  // ── Title + preamble ────────────────────────────────────────────────────────
  lines.push(`# Incident Postmortem — ${r.input.hint}`);
  lines.push('');
  lines.push(
    '_Draft generated by Horus — deterministic, no AI. Edit freely; Horus drafts, it does not dictate._',
  );
  lines.push('');
  lines.push(`**Confidence:** ${r.confidence.toFixed(2)}`);
  if (r.input.service) lines.push(`**Service:** ${r.input.service}`);
  if (r.input.since) lines.push(`**Since:** ${r.input.since}`);
  lines.push('');

  // ── Summary ─────────────────────────────────────────────────────────────────
  lines.push('## Summary');
  lines.push('');
  lines.push(r.summary);
  lines.push('');

  // ── Impact ──────────────────────────────────────────────────────────────────
  lines.push('## Impact');
  lines.push('');

  const impactEvidence = r.evidence.filter((e) => e.kind === 'impact');
  const hasBoundaryCrossings = r.timeline.boundaryCrossings.length > 0;

  if (impactEvidence.length > 0) {
    lines.push('The following impact signals were observed:');
    lines.push('');
    for (const e of impactEvidence) {
      lines.push(`- \`${shortId(e.id)}\` ${e.title}`);
    }
    lines.push('');
  }

  if (hasBoundaryCrossings) {
    lines.push('Async boundaries crossed during the incident:');
    lines.push('');
    for (const bc of r.timeline.boundaryCrossings) {
      const producer = bc.producer ?? '?';
      const worker = bc.worker ?? '?';
      lines.push(`- **${bc.queueName}**: ${producer} → ${worker}`);
    }
    lines.push('');
  }

  if (impactEvidence.length === 0 && !hasBoundaryCrossings) {
    lines.push('_No impact evidence was captured during this investigation._');
    lines.push('');
  }

  // Find a metrics gap if present — cite it for the precision caveat
  const metricsGap = r.gapAnalysis.gaps.find((g) => g.dimension === 'metrics');
  if (metricsGap) {
    lines.push(
      `> **Note:** Precise user/runtime impact (error rates, latency percentiles, affected user count) ` +
        `requires metrics that were unavailable during this investigation. ` +
        `${metricsGap.why} Next: ${metricsGap.nextSource}.`,
    );
  } else {
    lines.push(
      '> **Note:** Confirm precise user/runtime impact (error rates, affected user count) with your metrics provider.',
    );
  }
  lines.push('');

  // ── Timeline ────────────────────────────────────────────────────────────────
  lines.push('## Timeline');
  lines.push('');
  if (r.timeline.events.length === 0) {
    lines.push('_no timeline_');
  } else {
    for (const ev of r.timeline.events) {
      const at = ev.at ?? 'structural';
      lines.push(`${ev.order}. [${at}] ${ev.title}`);
    }
  }
  lines.push('');

  // ── Contributing factors ─────────────────────────────────────────────────────
  lines.push('## Contributing factors');
  lines.push('');

  const supportedHypotheses = r.hypotheses.filter((h) => h.verdict === 'supported');
  const commitEvidence = r.evidence.filter((e) => e.kind === 'commit');

  if (supportedHypotheses.length === 0 && commitEvidence.length === 0) {
    const topCause = r.suspectedCauses[0];
    if (topCause) {
      lines.push(
        `_No hypotheses reached 'supported' status. The leading suspected cause is unconfirmed:_`,
      );
      lines.push('');
      lines.push(`1. **(score ${topCause.finalScore.toFixed(2)}, ${topCause.band})** ${topCause.title}`);
    } else {
      lines.push(
        '_No confirmed contributing factors were identified. Further evidence is needed._',
      );
    }
  } else {
    if (r.causeChains !== undefined && r.causeChains.length > 0) {
      lines.push('The following causal sequences are supported by the collected evidence:');
      lines.push('');
      for (const chain of r.causeChains) {
        lines.push(`### ${chain.category} _(confidence ${chain.confidence.toFixed(2)})_`);
        lines.push('');
        lines.push(chain.summary);
        lines.push('');
        for (let i = 0; i < chain.steps.length; i++) {
          const step = chain.steps[i]!;
          const num = i + 1;
          const evCite =
            step.evidenceIds.length > 0
              ? ` — evidence: ${step.evidenceIds.map((id) => `\`${shortId(id)}\``).join(', ')}`
              : '';
          lines.push(`${num}. **[${step.role}]** ${step.label}${evCite}`);
        }
        lines.push('');
      }
    } else {
      if (supportedHypotheses.length > 0) {
        lines.push('The following factors are supported by the collected evidence:');
        lines.push('');
        for (const h of supportedHypotheses) {
          lines.push(
            `- **${h.category}:** ${h.statement} _(confidence ${h.confidence.toFixed(2)})_`,
          );
        }
      }
    }

    if (commitEvidence.length > 0) {
      if (supportedHypotheses.length > 0 || (r.causeChains?.length ?? 0) > 0) lines.push('');
      lines.push('Recent changes (commit evidence) present during this incident:');
      lines.push('');
      for (const e of commitEvidence) {
        lines.push(`- \`${shortId(e.id)}\` ${e.title}`);
      }
    }
  }
  lines.push('');

  // ── Root cause (candidate) ───────────────────────────────────────────────────
  lines.push('## Root cause (candidate)');
  lines.push('');

  const topHypothesis = supportedHypotheses[0];
  const topSuspectedCause = r.suspectedCauses[0];

  // Identify 1–2 gap dimensions for the caveat
  const gapDimensions = r.gapAnalysis.gaps
    .slice(0, 2)
    .map((g) => g.dimension)
    .join(', ');
  const gapCaveat =
    gapDimensions.length > 0
      ? `This candidate cannot be confirmed while evidence gaps remain (missing: ${gapDimensions}).`
      : 'Review the gap analysis and gather additional evidence before confirming.';

  if (topHypothesis) {
    lines.push(
      `**CANDIDATE** _(confidence ${topHypothesis.confidence.toFixed(2)})_: ${topHypothesis.statement}`,
    );
    lines.push('');
    lines.push(`_${gapCaveat}_`);
  } else if (topSuspectedCause) {
    lines.push(
      `**CANDIDATE** _(score ${topSuspectedCause.finalScore.toFixed(2)}, ${topSuspectedCause.band}, unconfirmed)_: ${topSuspectedCause.title}`,
    );
    lines.push('');
    lines.push(`_${gapCaveat}_`);
  } else {
    lines.push(
      '_No candidate root cause could be determined from the available evidence._',
    );
    lines.push('');
    lines.push(`_${gapCaveat}_`);
  }
  lines.push('');

  // ── Evidence ─────────────────────────────────────────────────────────────────
  lines.push('## Evidence');
  lines.push('');
  if (r.evidence.length === 0) {
    lines.push('_No evidence was collected._');
  } else {
    for (const e of r.evidence) {
      lines.push(`- ${shortId(e.id)} [${e.source}/${e.kind}] ${e.title}`);
    }
  }
  lines.push('');

  // ── Lessons learned ──────────────────────────────────────────────────────────
  lines.push('## Lessons learned');
  lines.push('');

  if (r.gapAnalysis.gaps.length === 0) {
    lines.push(
      'Good observability coverage for this investigation. Consider reviewing your alerting ' +
        'and on-call runbooks to ensure similar incidents are detected and scoped faster in future.',
    );
  } else {
    for (const gap of r.gapAnalysis.gaps) {
      lines.push(
        `- During this incident, **${gap.dimension}** was unavailable — ${gap.why} ` +
          `Wiring **${gap.nextSource}** would let the next investigation confirm or rule this out faster.`,
      );
    }
  }
  lines.push('');

  // ── Follow-up actions ────────────────────────────────────────────────────────
  lines.push('## Follow-up actions');
  lines.push('');

  // Merge structural next actions with gap-based actions so connector follow-ups
  // appear once, in clean language, tied to the dimension they close. This avoids
  // the noisy "Wire Add ..." duplication when gap.nextSource was already pushed
  // into report.nextActions by the engine.
  const checkboxItems: string[] = [];
  const seen = new Set<string>();

  // 1. Structural actions from the investigation pipeline (deduplicated).
  for (const action of r.nextActions) {
    if (!seen.has(action)) {
      seen.add(action);
      checkboxItems.push(action);
    }
  }

  // 2. Gap actions. If a gap's nextSource is already present as a raw structural
  //    action, replace that raw action with a single clean item that names both
  //    the action and the dimension it closes. Otherwise append the clean item.
  const seenGapSources = new Set<string>();
  for (const gap of r.gapAnalysis.gaps) {
    if (seenGapSources.has(gap.nextSource)) continue;
    seenGapSources.add(gap.nextSource);

    const cleanGapAction = `${gap.nextSource} to close the '${gap.dimension}' evidence gap`;
    if (seen.has(gap.nextSource)) {
      // Replace the raw nextSource action with the merged clean action.
      const idx = checkboxItems.indexOf(gap.nextSource);
      if (idx !== -1 && !seen.has(cleanGapAction)) {
        checkboxItems[idx] = cleanGapAction;
        seen.delete(gap.nextSource);
        seen.add(cleanGapAction);
      }
    } else if (!seen.has(cleanGapAction)) {
      seen.add(cleanGapAction);
      checkboxItems.push(cleanGapAction);
    }
  }

  if (checkboxItems.length === 0) {
    lines.push('- [ ] Review this postmortem with the team and decide on follow-ups.');
  } else {
    for (const item of checkboxItems) {
      lines.push(`- [ ] ${item}`);
    }
  }
  lines.push('');

  return lines.join('\n');
}
